package com.s8.io.bohr.beryllium.branch;

import static com.s8.api.bohr.BOHR_Keywords.CLOSE_JUMP;
import static com.s8.api.bohr.BOHR_Keywords.DEFINE_JUMP_COMMENT;
import static com.s8.api.bohr.BOHR_Keywords.DEFINE_JUMP_TIMESTAMP;
import static com.s8.api.bohr.BOHR_Keywords.OPEN_JUMP;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.s8.api.bytes.ByteOutflow;
import com.s8.api.bytes.MemoryFootprint;
import com.s8.io.bohr.beryllium.exception.BeIOException;
import com.s8.io.bohr.beryllium.object.BeObjectDelta;


/**
 * 
 *
 * @author Pierre Convert
 * Copyright (C) 2022, Pierre Convert. All rights reserved.
 * 
 */
public class BeBranchDelta {




	/**
	 * Mandatriy version
	 */
	public final long targetVersion;


	/**
	 * the revision generated by applying this delta to previous rev
	 */
	private boolean hasTimestamp;

	/**
	 * 
	 */
	private long timestamp;


	/**
	 * 
	 */
	private boolean hasComment;

	/**
	 * 
	 */
	private String comment;


	/**
	 * 
	 */
	public List<BeObjectDelta> objectDeltas = new ArrayList<>();


	/**
	 * 
	 */
	public long lastAssignedIndex = -1;


	/**
	 * 
	 */
	public BeBranchDelta(long version) {
		super();
		this.targetVersion = version;
	}

	
	
	public void setComment(String comment) {
		this.hasComment = true;
		this.comment = comment;
	}
	
	
	public void setTimestamp(long timestamp) {
		this.hasTimestamp = true;
		this.setTimestamp(timestamp);
	}

	/**
	 * 
	 * @param delta
	 */
	public void appendObjectDelta(BeObjectDelta delta) {
		objectDeltas.add(delta);
	}



	/**
	 * 
	 * @param graph
	 * @throws NdIOException
	 */
	public void consume(BeTable table) throws BeIOException {
		/* check version */
		
	
		for(BeObjectDelta objectDelta : objectDeltas) { 
			objectDelta.consume(table); 
		}
	}




	public void serialize(BeOutbound outbound, ByteOutflow outflow) throws IOException {

		outflow.putUInt8(OPEN_JUMP);
		
		outflow.putUInt64(targetVersion);
		
		
		if(hasTimestamp) {
			outflow.putUInt8(DEFINE_JUMP_TIMESTAMP);
			outflow.putUInt64(timestamp);
		}
		
		if(hasComment) {
			outflow.putUInt8(DEFINE_JUMP_COMMENT);
			outflow.putStringUTF8(comment);
		}

		// compose common database
		//codebaseIO.compose(outflow, false);
		for(BeObjectDelta objectDelta : objectDeltas) { 
		
			
			objectDelta.serialize(outbound, outflow); 
		}


		outflow.putUInt8(CLOSE_JUMP);
	}


	public void computeFootprint(MemoryFootprint weight) {
		weight.reportInstance();
		objectDeltas.forEach(delta -> delta.computeFootprint(weight));
	}

}